#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Stash unstaged changes
git stash -q --keep-index

cp ./.ask/config ./.ask/config_bkp
rm ./.ask/config
cp ./.ask/config_base ./.ask/config


# Stage updated files
git add -u

# Re-apply original unstaged changes
git stash pop -q

cp ./.ask/config_bkp ./.ask/config
rm ./.ask/config_bkp